name: QuickPOS CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - "feature/**"
      - "bugfix/**"

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer

      - name: Install Dependencies
        run: composer install

      - name: Run PHPCS
        run: vendor/bin/phpcs

  automated-tests:
    name: Automated Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer

      - name: Install Dependencies
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit tests

  syntax-check:
    name: PHP Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest

      - name: Run PHP Syntax Check
        run: |
          find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 php -l